### ISSUE TITLE
simplification with numeric MX

### ISSUE THREAD

**Issue by jgillis** [casadi/casadi#1862] opened 2016-09-06 13:10 UTC
We have `vertsplit(MX.zeros(8,6),4)` -> `[MX(zeros(4x6, dense)), MX(zeros(4x6, dense))]`
but `vertsplit(MX.ones(8,6),4)` does not give `[MX(ones(4x6, dense)), MX(ones(4x6, dense))]`

**Comment by jgillis** [comment] 2016-09-06 13:27
Inspired by

```
from casadi import *


x_P = MX.sym('x_P')
y_P = MX.sym('y_P')

P = vertcat(x_P,y_P)
A = vertcat(0,0)


k = 10
L_AB = 1
m = MX.sym('m')
g = 9.81


d_AB = norm_2(A-P)

V = 1.0/2*k*(d_AB-L_AB)**2 + m*g*y_P

print jacobian(V,P)
```

**Comment by jaeandersson** [comment] 2016-09-06 20:33
Arguably a duplicate of #172

**Comment by jgillis** [comment] 2016-09-09 12:49
Its a weaker form of #172 indeed.

**Closed** 2020-07-20 22:05 UTC
