### ISSUE TITLE
Remove HomotopyNLPSolver

### ISSUE THREAD

**Issue by jaeandersson** [casadi/casadi#1430] opened 2015-05-24 12:44 UTC
From what I can tell, HomotopyNLPSolver is not used for anything, which is not surprising, since it doesn't even have an exposed constructor.

I think the functionality of solving sequences of similar NLPs is important, but I don't believe that having a dedicated class deriving from Function is the correct way forward.

@jgillis?

**Comment by jgillis** [comment] 2015-06-27 19:57
duplicate of #881 . It was only ever experimental.

**Closed by jgillis** 2015-06-27 19:57 UTC
