### ISSUE TITLE
MATLAB equivalent to python function(method?) struct_symSX () and entry()

### ISSUE THREAD

**Issue by olzhas** [casadi/casadi#2022] opened 2017-06-12 11:51 UTC
Hi,
could you please tell the MATLAB equivalent to python function(method?) struct_symSX () and entry() ?

thank you in advance for the assistance.

**Comment by jgillis** [comment] 2017-06-12 13:13
Duplicate of #1388 
No progress yet on this part.
Perhaps you could have a look at @JonasKoenemann or https://gist.github.com/jgillis/de15f427174858f15414

**Closed by jgillis** 2017-06-12 13:13 UTC
