### ISSUE TITLE
Wrong input dimension in integrator/simulator-inputs -> "Please notify the CasADi developers."

### ISSUE THREAD

**Issue by adbuerger** [casadi/casadi#1455] opened 2015-06-27 12:02 UTC
When calling `Integrator.setInput()` or `Simulator.setInput()` with values whose dimensions do not match the corresponding variables within the integrator/simulator (like e. g. using 5 states, but only supporting 4 input values for "x0"), this error message is thrown:

    RuntimeError:  on line 378 of file "/home/casadibot/slaves/linuxbot/release-update-minimal/source/./casadi/core/mx/../function/io_interface.hpp"
    The assertion "val.size()==this->nnz()" on line 2936 of file "/home/casadibot/slaves/linuxbot/release-update-minimal/source/./casadi/core/sx/../matrix/matrix_impl.hpp" failed. 
    Please notify the CasADi developers.
    Occurred at iind = 2.

Can the error message be improved in a way so that the user directly knows what he did wrong, and that he (probably?) does not have to contact you?

**Comment by jaeandersson** [comment] 2015-06-27 12:51
I would say that this is a duplicate of #1442.

**Closed by jaeandersson** 2015-06-27 12:51 UTC
Labels: duplicate
