### ISSUE TITLE
'which_depends' not defined for External when using codegen with bonmin

### ISSUE THREAD

**Issue by thomasfork** [casadi/casadi#3427] opened 2023-10-24 20:53 UTC
Creating an nlpsol solver with bonmin and compiled code raises an error (passes with ipopt). 

Below is a minimal working example on linux using GCC. (however this happens on windows as well)
Removing the "discrete" option to nlpsol has no impact.

```
from casadi import * 
import subprocess

J = 0
w = SX.sym('w', 3)
g = w**2
discrete = [True, False, False]

# Create an NLP solver
nlp_prob = {'f': J, 'x': w, 'g': g}
nlp_solver = nlpsol('nlp_solver', 'bonmin', nlp_prob, {"discrete": discrete});
#nlp_solver = nlpsol('nlp_solver', 'ipopt', nlp_prob); # Solve relaxed problem

############################## try to codegen the solver #############################
source_path  = 'lv.c'
dest_path = 'lv.so'
nlp_solver.generate_dependencies(source_path)
cmd = f'gcc -fPIC -shared -O3 {source_path} -o {dest_path}'
subp = subprocess.Popen(cmd, stdout=subprocess.PIPE, shell=True)
print('Compiling solver...')
subp.wait()

############################## try to codegen the solver #############################
solver = nlpsol('solver','bonmin',dest_path,{"discrete": discrete})   # raises  .../casadi/core/function_internal.cpp:3501: 'which_depends' not defined for External
#solver = nlpsol('solver','ipopt',dest_path)                          # passes

```

this is the traceback:
```
Traceback (most recent call last):
  File "/home/thomas/Shared/GitHub/vehicle_3d/examples/misc.py", line 25, in <module>
    solver = nlpsol('solver','bonmin',dest_path,{"discrete": discrete})   # raises  .../casadi/core/function_internal.cpp:3501: 'which_depends' not defined for External
  File "/home/thomas/.local/lib/python3.10/site-packages/casadi/casadi.py", line 28956, in nlpsol
    return _casadi.nlpsol(*args)
RuntimeError: .../casadi/core/function_internal.cpp:145: Error calling BonminInterface::init for 'solver':
Error in Function::which_depends for 'nlp' [External] at .../casadi/core/function.cpp:1769:
.../casadi/core/function_internal.cpp:3558: 'which_depends' not defined for External
```

**Comment by jgillis** [comment] 2023-11-03 20:06
Duplicate of #3257

**Closed** 2023-11-03 21:27 UTC
