### ISSUE TITLE
idas doesn't provide grad_z_p

### ISSUE THREAD

**Issue by kozachynskyi** [casadi/casadi#2806] opened 2021-07-21 16:28 UTC
Hi Everyone,

In the gist below I try to solve very simplified Parameter Estimation problem of a DAE Model with ``ipopt``. DAE is simulated either with ``idas`` or with ``collocation``. Objective function is solely dependent on "algebraic variables".

If you run code below you'll notice, that ``ipopt`` calculates ``grad_f_x`` of the objective function as zero, if ``idas`` is used. I would expect some small value, but not zero. With ``collocation`` I get expected small value.

Is it possible that ``idas`` interface doesn't implement generation of grad_z_p, thus ``ipopt`` cannot procede?

https://gist.github.com/kozachynskyi/de6a3551b3717e6a87c4c20f4b10a81d

**Comment by jgillis** [comment] 2021-07-22 08:12
Thanks for taking the time to report this issue.
It seems there is a bug in reverse mode for `zf` of any integrator.
You may work around it by forcing forward mode ("ad_weight":0  option for integrators), but this is of course far from ideal if you have a lot of parameters in your optimization problem.


To reproduce:

```
from casadi import *
# Example taken from IDAS Tutorial

# http://casadi.sourceforge.net/api/html/db/d58/integrators_2idas_8py-example.html

from numpy import *
from pylab import *
from casadi import *


L = MX.sym("L")
g = MX.sym("g")

#! differential states
x=MX.sym("x")
y=MX.sym("y")
u=MX.sym("u")
v=MX.sym("v")

#! algebraic states
lambd=MX.sym("lambda")

#! All states and parameters
x_all = vertcat(x,u,y,v)
z_all = lambd
p_all = vertcat(L,g)

#! We construct the DAE system
ode = vertcat(u,lambd*x)
alg = vertcat(x**2+y**2-L**2, u*x+v*y,u**2-g*y+v**2+L**2*lambd)
x_all = vertcat(x,u)
z_all = vertcat(y,v,lambd)
dae = {'x':x_all, 'z':z_all, 'p':p_all, 'ode':ode, 'alg':alg}
f = Function('f', [x_all, z_all, p_all], [ode, alg], ['x', 'z', 'p'], ['ode', 'alg'])

#! the initial state of the pendulum
P_ = [5,10] 
X_ = [3,-1.0/3] 
XDOT_ = [-1.0/3,1147.0/240] 
Z_ = [4,1.0/4,1147.0/720] 

for ad_weight in [0,1]:
  collocation_solver = integrator('I', 'collocation', dae, {'t0':0, 'tf':1,"ad_weight":ad_weight})

  res = collocation_solver(p=vertcat(5,g), x0=X_, z0=Z_)
  G = Function('g',[g],[gradient(res["zf"][0],g)])
  print("ad_weight",ad_weight,G(5))
```

**Comment by jaeandersson** [comment] 2021-07-22 11:10
I'll have a look

**Comment by kozachynskyi** [comment] 2021-07-22 11:15
@jgillis Thank you for a fast answer. "ad_weight":0 works, as expected. Another reason, why it's far from ideal solution: now my algebraic equations also have to be properly scaled)

**Comment by jaeandersson** [comment] 2021-08-23 16:04
Another way around it by the way is to create a `rootfinder` instance (using `alg`) to recalculate "zf" from "xf". Derivatives should then be correctly calculated since the `zf` from the integrator will then enter as an initial guess for the solution. Since the rootfinder instance is initialized at the solution, solution should be trivial.

**Comment by kozachynskyi** [comment] 2023-04-08 14:52
@jaeandersson Hi Joel, thanks Casadi Team for your incredible work with integrators in 3.6.0. 

Looks like the bug still exists in 3.6.0

**Comment by jaeandersson** [comment] 2023-04-08 16:00
> Thanks for taking the time to report this issue. It seems there is a bug in reverse mode for `zf` of any integrator. You may work around it by forcing forward mode ("ad_weight":0 option for integrators), but this is of course far from ideal if you have a lot of parameters in your optimization problem.
> 
> To reproduce:
> 
> ```python
> from casadi import *
> # Example taken from IDAS Tutorial
> 
> # http://casadi.sourceforge.net/api/html/db/d58/integrators_2idas_8py-example.html
> 
> from numpy import *
> from pylab import *
> from casadi import *
> 
> 
> L = MX.sym("L")
> g = MX.sym("g")
> 
> #! differential states
> x=MX.sym("x")
> y=MX.sym("y")
> u=MX.sym("u")
> v=MX.sym("v")
> 
> #! algebraic states
> lambd=MX.sym("lambda")
> 
> #! All states and parameters
> x_all = vertcat(x,u,y,v)
> z_all = lambd
> p_all = vertcat(L,g)
> 
> #! We construct the DAE system
> ode = vertcat(u,lambd*x)
> alg = vertcat(x**2+y**2-L**2, u*x+v*y,u**2-g*y+v**2+L**2*lambd)
> x_all = vertcat(x,u)
> z_all = vertcat(y,v,lambd)
> dae = {'x':x_all, 'z':z_all, 'p':p_all, 'ode':ode, 'alg':alg}
> f = Function('f', [x_all, z_all, p_all], [ode, alg], ['x', 'z', 'p'], ['ode', 'alg'])
> 
> #! the initial state of the pendulum
> P_ = [5,10] 
> X_ = [3,-1.0/3] 
> XDOT_ = [-1.0/3,1147.0/240] 
> Z_ = [4,1.0/4,1147.0/720] 
> 
> for ad_weight in [0,1]:
>   collocation_solver = integrator('I', 'collocation', dae, {'t0':0, 'tf':1,"ad_weight":ad_weight})
> 
>   res = collocation_solver(p=vertcat(5,g), x0=X_, z0=Z_)
>   G = Function('g',[g],[gradient(res["zf"][0],g)])
>   print("ad_weight",ad_weight,G(5))
> ```

Thanks for reporting. I'll have a look and we'll try to include the fix in the next minor release (3.6.1)

**Comment by jaeandersson** [comment] 2023-04-08 16:37
Here is a more minimal example:
```python

from casadi import *
# Example taken from IDAS Tutorial

# http://casadi.sourceforge.net/api/html/db/d58/integrators_2idas_8py-example.html

from numpy import *
from pylab import *
from casadi import *


L = 5.
g = MX.sym("g")

#! differential states
x=MX.sym("x")
y=MX.sym("y")
u=MX.sym("u")
v=MX.sym("v")

#! algebraic states
lambd=MX.sym("lambda")

#! All states and parameters
x_all = vertcat(x,u,y,v)
z_all = lambd

#! We construct the DAE system
ode = vertcat(u,lambd*x)
alg = vertcat(x**2 + y**2 - L**2, u*x + v*y, u**2 - g*y + v**2 + L**2 * lambd)
x_all = vertcat(x,u)
z_all = vertcat(y,v,lambd)
dae = {'x':x_all, 'z':z_all, 'p':g, 'ode':ode, 'alg':alg}

#! the initial state of the pendulum
X_ = [3,-1.0/3] 
Z_ = [4,1.0/4,1147.0/720] 

I_adj = integrator('I', 'collocation', dae, dict(nadj = 1))
res = I_adj(p = 5, x0=X_, z0=Z_, adj_zf = [1, 0, 0])
print("adjoint sensitivity analysis", res['adj_p'])

I_fwd = integrator('I', 'collocation', dae, dict(nfwd = 1))
res = I_fwd(p = [5, 1], x0=horzcat(X_, DM.zeros(2)), z0 = horzcat(Z_, DM.zeros(3)))
print("forward sensitivity analysis", res['zf'][0, 1])
```

**Comment by jaeandersson** [comment] 2023-04-08 18:36
Issue is that adjoint seeds corresponding to zf aren't propagated appropriately to the backwards state. Same issue for Collocation and IDAS.

**Comment by jaeandersson** [comment] 2023-04-14 00:54
Resolved for Collocation in #3099. IDAS case should be resolved by #3104

**Comment by jaeandersson** [comment] 2023-04-17 19:49
@kozachynskyi This issue should be resolved the `develop` branch of CasADi. If you are able to test this feature with your application before the 3.6.1 release, it would be great.

**Closed by jaeandersson** 2023-04-17 19:49 UTC
Labels: bug

**Comment by jaeandersson** [comment] 2023-04-17 19:59
Running the first script above, which relies on the "collocation" integrator, now gives:
```
CasADi - 2023-04-17 14:51:54 WARNING("The options 't0', 'tf', 'grid' and 'output_t0' have been deprecated. Set the time grid by proving additional argument to the 'integrator' call instead.") [.../casadi/core/integrator.cpp:497]
CasADi - 2023-04-17 14:51:54 WARNING("The options 't0', 'tf', 'grid' and 'output_t0' have been deprecated. Set the time grid by proving additional argument to the 'integrator' call instead.") [.../casadi/core/integrator.cpp:497]
ad_weight 0 -0.250469
CasADi - 2023-04-17 14:51:54 WARNING("The options 't0', 'tf', 'grid' and 'output_t0' have been deprecated. Set the time grid by proving additional argument to the 'integrator' call instead.") [.../casadi/core/integrator.cpp:497]
CasADi - 2023-04-17 14:51:54 WARNING("The options 't0', 'tf', 'grid' and 'output_t0' have been deprecated. Set the time grid by proving additional argument to the 'integrator' call instead.") [.../casadi/core/integrator.cpp:497]
ad_weight 1 -0.250469
```
If you replace the integrator with "idas", you get:
```
CasADi - 2023-04-17 14:53:16 WARNING("The options 't0', 'tf', 'grid' and 'output_t0' have been deprecated. Set the time grid by proving additional argument to the 'integrator' call instead.") [.../casadi/core/integrator.cpp:497]
CasADi - 2023-04-17 14:53:16 WARNING("The options 't0', 'tf', 'grid' and 'output_t0' have been deprecated. Set the time grid by proving additional argument to the 'integrator' call instead.") [.../casadi/core/integrator.cpp:497]
ad_weight 0 -0.250469
CasADi - 2023-04-17 14:53:16 WARNING("The options 't0', 'tf', 'grid' and 'output_t0' have been deprecated. Set the time grid by proving additional argument to the 'integrator' call instead.") [.../casadi/core/integrator.cpp:497]
CasADi - 2023-04-17 14:53:16 WARNING("The options 't0', 'tf', 'grid' and 'output_t0' have been deprecated. Set the time grid by proving additional argument to the 'integrator' call instead.") [.../casadi/core/integrator.cpp:497]
ad_weight 1 -0.250285
```
Note that the "collocation" integrator gives exactly the same value for forward and adjoint sensitivity analysis. This is expected - the adjoint mode for fixed-step integrators now calls the analytic differentiation routine for the forward step. For IDAS - where sensitivities are calculated using a variational approach, you see an accuracy loss. Since the steps of the backward integration aren't necessarily the same as the steps of the forward integration, this should be expected.

**Comment by jaeandersson** [comment] 2023-04-17 20:28
Here is some more testing results regarding accuracy:

```python
from casadi import *
# Example taken from IDAS Tutorial

# http://casadi.sourceforge.net/api/html/db/d58/integrators_2idas_8py-example.html

from numpy import *
from pylab import *
from casadi import *


L = 5.
g = MX.sym("g")

#! differential states
x=MX.sym("x")
y=MX.sym("y")
u=MX.sym("u")
v=MX.sym("v")

#! algebraic states
lambd=MX.sym("lambda")

#! All states and parameters
x_all = vertcat(x,u,y,v)
z_all = lambd

#! We construct the DAE system
ode = vertcat(u,lambd*x)
alg = vertcat(x**2 + y**2 - L**2, u*x + v*y, u**2 - g*y + v**2 + L**2 * lambd)
x_all = vertcat(x,u)
z_all = vertcat(y,v,lambd)
dae = {'x':x_all, 'z':z_all, 'p':g, 'ode':ode, 'alg':alg}

#! the initial state of the pendulum
X_ = [3,-1.0/3] 
Z_ = [4,1.0/4,1147.0/720] 

# Compare different tolerances
print(r"{:<15}  {:<15}  {:<15}  {:15}".format('Tolerance', 'Forward', 'Adjoint', 'Difference'))
for tol in [1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9, 1e-10]:
    # Forward sensitivity analysis
    I_fwd = integrator('I', 'idas', dae, dict(nfwd = 1, abstol = tol, reltol = tol))
    res = I_fwd(p = [5, 1], x0=horzcat(X_, DM.zeros(2)), z0 = horzcat(Z_, DM.zeros(3)))
    dzf_dp_fwd = float(res['zf'][0, 1])

    # Adjoint sensitivity analysis
    I_adj = integrator('I', 'idas', dae, dict(nadj = 1, abstol = tol, reltol = tol))
    res_adj = I_adj(p = 5, x0=X_, z0=Z_, adj_zf = [1, 0, 0])
    dzf_dp_adj = float(res_adj['adj_p'])

    # Relative difference
    dzf_dp_diff = abs(dzf_dp_adj - dzf_dp_fwd) / max(abs(dzf_dp_adj), abs(dzf_dp_fwd))

    # Print line
    print(r"{:e}  {:e}  {:e}  {:e}".format(tol, dzf_dp_fwd, dzf_dp_adj, dzf_dp_diff))
```
Outputs:
```
Tolerance        Forward          Adjoint          Difference     
1.000000e-03  -2.501474e-01  -2.483792e-01  7.068420e-03
1.000000e-04  -2.505077e-01  -2.502460e-01  1.044650e-03
1.000000e-05  -2.505009e-01  -2.502892e-01  8.451271e-04
1.000000e-06  -2.504680e-01  -2.501698e-01  1.190692e-03
1.000000e-07  -2.504686e-01  -2.504622e-01  2.551046e-05
1.000000e-08  -2.504688e-01  -2.504683e-01  2.186489e-06
1.000000e-09  -2.504688e-01  -2.504162e-01  2.099622e-04
1.000000e-10  -2.504688e-01  -2.504687e-01  3.625531e-07
```

It looks like the differences do get smaller with tolerances, so I tend to think that this is just an artifact of the variational approach to sensitivity analysis. The backward step sizes do not seem to align with forward step sizes.

**Comment by kozachynskyi** [comment] 2023-04-18 09:50
> @kozachynskyi This issue should be resolved the `develop` branch of CasADi. If you are able to test this feature with your application before the 3.6.1 release, it would be great.

Hi Joel, thanks for your work! I have tested the "develop" branch in my application, where I solve parameter estimation optimization problem with nlpsol, where integrator is used to generate objective function. Collocation works as expected, and idas unfortunately does not. Ipopt moves very slowly to the real minima, which actually tells me that the Jacobian is not correct. I tried increasing the tolerance of idas, and it had an effect for the first ipopt iterations, but after that I get very slow convergence.

It's hard to share my code as a snippet, I'll try to come up with a solution to ilustrate the problem, or I'll just give you a personal access.

**Comment by kozachynskyi** [comment] 2023-04-18 11:22
@jaeandersson 

Here is an example, you can look yourself

```python
from casadi import *
# Example taken from IDAS Tutorial

# http://casadi.sourceforge.net/api/html/db/d58/integrators_2idas_8py-example.html

from numpy import *
from pylab import *
from casadi import *


L = 5.
g = MX.sym("g")

#! differential states
x=MX.sym("x")
y=MX.sym("y")
u=MX.sym("u")
v=MX.sym("v")

#! algebraic states
lambd=MX.sym("lambda")

#! All states and parameters
x_all = vertcat(x,u,y,v)
z_all = lambd

#! We construct the DAE system
ode = vertcat(u,lambd*x)
alg = vertcat(x**2 + y**2 - L**2, u*x + v*y, u**2 - g*y + v**2 + L**2 * lambd)
x_all = vertcat(x,u)
z_all = vertcat(y,v,lambd)
dae = {'x':x_all, 'z':z_all, 'p':vertcat(g), 'ode':ode, 'alg':alg}

#! the initial state of the pendulum
X_ = [3,-1.0/3] 
Z_ = [4,1.0/4,1147.0/720] 


def fun_eval(fixed, integrator_name, tol):
    if integrator == "idas":
        opts = dict(abstol = tol, reltol = tol)
    else:
        opts = {}
        
    I = integrator('I', integrator_name, dae, 0, 0.1)
    x0=X_
    z0=Z_
    all_z = []

    if fixed:
        p = 5
    else:
        p = g

    for i in range(4):
        one_step = I(p = p, x0=x0, z0=z0)
        x0=one_step["xf"]
        z0=one_step["zf"]
        all_z.append(z0)

    return hcat(all_z)

for integrator_name in ["idas", "collocation"]:
    obj = fun_eval(False, integrator_name, 1e-6) - fun_eval(True, integrator_name, 1e-6)
    solver = nlpsol("s", "ipopt", dict(x=g, f=sumsqr(obj)))

    print(solver(x0=[4]))

```

**Comment by kozachynskyi** [comment] 2023-04-18 11:40
So I think I found some hint: I modified code from previous post to use objective function with "xf" and "zf". This code can be run with 3.5 and 3.6 casadi, and here is a result:

- Looks like "develop" branch does actually provides jac_zf correctly, in comparison to 3.6.0, so this issue can be closed
- Convergence of IPOPT in 3.6 and "develop" is much slower than in 3.5.5 -> this probably requires a new issue ...
```python
from casadi import *
# Example taken from IDAS Tutorial

# http://casadi.sourceforge.net/api/html/db/d58/integrators_2idas_8py-example.html

from numpy import *
from pylab import *
from casadi import *


L = 5.
g = MX.sym("g")

#! differential states
x=MX.sym("x")
y=MX.sym("y")
u=MX.sym("u")
v=MX.sym("v")

#! algebraic states
lambd=MX.sym("lambda")

#! All states and parameters
x_all = vertcat(x,u,y,v)
z_all = lambd

#! We construct the DAE system
ode = vertcat(u,lambd*x)
alg = vertcat(x**2 + y**2 - L**2, u*x + v*y, u**2 - g*y + v**2 + L**2 * lambd)
x_all = vertcat(x,u)
z_all = vertcat(y,v,lambd)
dae = {'x':x_all, 'z':z_all, 'p':vertcat(g), 'ode':ode, 'alg':alg}

#! the initial state of the pendulum
X_ = [3,-1.0/3] 
Z_ = [4,1.0/4,1147.0/720] 


def fun_eval(fixed, integrator_name, tol):
    opts = {"t0": 0, "tf": 0.1}
    if integrator == "idas":
        opts[abstol] = tol
        opts[reltol] = tol
        
    I = integrator('I', integrator_name, dae, opts)
    x0=X_
    z0=Z_
    all_x = []
    all_z = []

    if fixed:
        p = 5
    else:
        p = g

    for i in range(8):
        one_step = I(p = p, x0=x0, z0=z0)
        x0=one_step["xf"]
        z0=one_step["zf"]
        all_x.append(x0)
        all_z.append(z0)

    return hcat(all_x), hcat(all_z)

for integrator_name in ["idas", "collocation"]:
    for switch in range(2):
        obj = fun_eval(False, integrator_name, 1e-6)[switch] - fun_eval(True, integrator_name, 1e-6)[switch]
        solver = nlpsol("s", "ipopt", dict(x=g, f=sumsqr(obj)))

        print(solver(x0=[4], lbx=[3], ubx=[6]))

```

**Comment by jaeandersson** [comment] 2023-04-18 18:44
I'm not convinced there is anything wrong. You are using default tolerances for IPOPT, which I think is 1e-8. But the tolerance for IPOPT is 1e-6. For Collocation that should be ok, because the adjoint derivative will be the exact derivative of the forward integration. For IDAS, derivatives are calculated using IDAS support for adjoint sensitivities, which in general only is active up to the set tolerance. So the noise of the calculation will be larger than IPOPT. If you use IDAS + adjoint differentiation, you would want the IPOPT tolerances to be at least 1 or 2 orders of magnitude larger than the integrator tolerance.  For IDAS + forward differentiation, you should be fine since CasADi is doing the augmentation of the system.

We are wrapping up 3.6.1 now so I don't think any more changes here will make it into the release. I'll have a look what happen if I use a rootfinder instance to propagate the "zf" derivatives, but it won't make it into the release.

**Comment by kozachynskyi** [comment] 2023-04-19 09:48
Hi Joel, I'm sorry I wasn't precise in my wording: In 3.6.1, Jacobian of algebraic variables definitely works. This issue is closed. Thanks again for your work.

I will open a new issue to share a code with you where idas performance has changed with 3.6.0 compared to 3.5.5.
