### ISSUE TITLE
Large Jacobian when subindexing MX structs for continuity constraints

### ISSUE THREAD

**Issue by JonasKoenemann** [casadi/casadi#1464] opened 2015-07-01 08:42 UTC
Hi!

I implemented Multiple Shooting for a 3D free-flight aircraft model 
using structs to structure the optimization variables:
```
    V = struct_symMX([
        entry("X",  struct=x,repeat=N+1),
        entry("U", struct=u, repeat=N)
    ])
```
and 
```
    x = struct_symMX([
        entry("p", shape=3),        # position 
        entry("v", shape=3),        # velocity
        entry("R", shape=(3,3)),    # rotation
        entry("w", shape=3)         # rotational velocity
    ])
```
Now I implemented two ways to enforce the continuity constraints. Both ways give the same solution but the second way is much slower and has a much larger number of non-zeros in the equality constraint Jacobian.

In the first way i enforce the continuity constraint on the complete state at once.
```
        g.append(xf-V['X',k+1])
        gmin.append(np.zeros(x.size))
        gmax.append(np.zeros(x.size))
```
where xf is the state after rk4 integration from V['X',k].

In the second way i enforce the continuity constraints for all substructures separately (which should be the same in the end):
```        
        g.append(xf['p'] - V['X',k+1,'p'])
        gmin.append(np.zeros(3)); gmax.append(np.zeros(3))
        
        g.append(xf['v'] - V['X',k+1,'v'])
        gmin.append(np.zeros(3)); gmax.append(np.zeros(3))
        
        g.append(xf['w'] - V['X',k+1,'w'])
        gmin.append(np.zeros(3)); gmax.append(np.zeros(3))
        
        g.append(xf['R'] - V['X',k+1,'R'])
        gmin.append(np.zeros(9)); gmax.append(np.zeros(9))
```

For comparison the output of IPOPT of way 1 gives:
```
Number of nonzeros in equality constraint Jacobian...:    34645
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:    17100

Total number of variables............................:     2118
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:     1825
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  0.0000000e+00 1.00e+01 0.00e+00  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  4.3490963e-01 1.07e-01 2.05e-01  -1.0 7.68e+01    -  1.00e+00 1.00e+00h  1
   2  2.5937220e-01 3.20e-02 7.10e-02  -1.7 2.49e+00    -  1.00e+00 1.00e+00h  1
   3  2.7241829e-01 8.53e-03 1.84e-02  -2.5 6.49e-01    -  1.00e+00 1.00e+00h  1
   4  2.6806943e-01 3.71e-04 6.24e-04  -3.8 5.67e-01    -  1.00e+00 1.00e+00h  1
   5  2.6823950e-01 2.55e-06 1.05e-05  -5.7 9.24e-02    -  1.00e+00 1.00e+00h  1
   6  2.6824071e-01 5.04e-11 6.07e-11  -8.6 2.93e-04    -  1.00e+00 1.00e+00h  1

Number of Iterations....: 6

Total CPU secs in IPOPT (w/o function evaluations)   =      0.293
Total CPU secs in NLP function evaluations           =      1.404
```

And for the second way the number of nonzeros in equality constraint Jacobian is huge, and thus the computation time much larger. It does one more iteration but otherwise the iterations look identically:

```
Number of nonzeros in equality constraint Jacobian...:  2034081
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:    17100

Total number of variables............................:     2118
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:     1825
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  0.0000000e+00 1.00e+01 0.00e+00  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  4.3490963e-01 1.07e-01 2.05e-01  -1.0 7.68e+01    -  1.00e+00 1.00e+00h  1
   2  2.5937223e-01 3.20e-02 7.10e-02  -1.7 2.49e+00    -  1.00e+00 1.00e+00h  1
   3  2.7241827e-01 8.53e-03 1.84e-02  -2.5 6.49e-01    -  1.00e+00 1.00e+00h  1
   4  2.6806943e-01 3.71e-04 6.24e-04  -3.8 5.67e-01    -  1.00e+00 1.00e+00h  1
   5  2.6823950e-01 2.55e-06 1.05e-05  -5.7 9.24e-02    -  1.00e+00 1.00e+00h  1
   6  2.6824071e-01 1.71e-11 1.96e-08  -8.6 7.34e-05  -3.6 1.00e+00 1.00e+00h  1
   7  2.6824071e-01 1.81e-11 8.60e-11  -9.0 2.20e-04    -  1.00e+00 1.00e+00h  1

Number of Iterations....: 7

Total CPU secs in IPOPT (w/o function evaluations)   =     50.301
Total CPU secs in NLP function evaluations           =      3.468
```

The reason why is want to split the constraints is that i want to remove some continuity constraints on the rotation matrix and add orthonormality constraints (and still have LICQ).

I am attaching both full implementation which should run out of the box. Its quiet large files but most of it is the dynamics. You can find the continuity constraints from line 237.

As i can not upload the files here, you find them in the cloud:
way1: [plane_optimization_fast.py](https://cloud.syscop.de/index.php/s/Gsx7nKtsjUnp34z)
way2: [plane_optimization_slow.py](https://cloud.syscop.de/index.php/s/BMTCvotjYrzZUJ5)

Thank you for the help!
Jonas

**Comment by jgillis** [comment] 2015-07-01 09:15
Hello Jonas, thanks for reporting this issue.
I can reproduce this bug on v2.3.0, but on our develop branch the bug is not present.

If I can identity the bug quickly, I may backport a fix and do a 2.3.1...

**Comment by jgillis** [comment] 2015-07-01 09:29
Reduced to

```py
from casadi import *
from casadi.tools import *

u = struct_symSX([
    entry("ail"), # roll
    entry("elev"), # pitch
    entry("rudder") # yaw
])

x = struct_symSX([
    entry("p", shape=3),
    entry("v", shape=3),
    entry("R", shape=(3,3)),
    entry("w", shape=3)
])

g = []
g2 = []

N = 10

rk4 = SXFunction([x,u],[x.cat+u.cat[0]])
rk4.init()

V = struct_symMX([
    entry("X",  struct=x,repeat=N+1),
    entry("U", struct=u, repeat=N)
])

for k in range(N):
    
    [xf] = rk4([V['X',k],V['U',k]])
    xf = x(xf)

    g.append(xf['p'] - V['X',k+1,'p'])
    g.append(xf['v'] - V['X',k+1,'v'])
    g.append(xf['w'] - V['X',k+1,'w'])
    g.append(xf['R'] - V['X',k+1,'R'])

    g2.append(xf-V['X',k+1])

gcat = veccat(g)
print jacobian(gcat,V).size()

gcat2 = veccat(g2)
print jacobian(gcat2,V).size()

```

**Comment by jgillis** [comment] 2015-07-01 09:39
Further reduced:

```py
from casadi import *

u = SX.sym("u")
x = SX.sym("x",6)

g = []
g2 = []

N = 10

rk4 = SXFunction([x,u],[x+u])
rk4.init()

V = MX.sym("V",(N+1)*6+N)
VX,VU = vertsplit(V,[0,(N+1)*6,(N+1)*6+N])

VXk = vertsplit(VX,6)
VUk = vertsplit(VU,1)

for k in range(N):
    
    [xf] = rk4([VXk[k],VUk[k]])

    xfp = vertsplit(xf,3)
    vp = vertsplit(VXk[k+1],3)

    g.append(xfp[0] - vp[0])
    g.append(xfp[1] - vp[1])

    g2.append(xf-VXk[k+1])

gcat = veccat(g)
print jacobian(gcat,V).size()

gcat2 = veccat(g2)
print jacobian(gcat2,V).size()
```

**Comment by jgillis** [comment] 2015-07-01 09:44
Further reduced:

```py
from casadi import *

n = 6
x = SX.sym("x",n)
u = SX.sym("u")

g = []
g2 = []

N = 10

rk4 = SXFunction([x,u],[x+u])
rk4.init()

V = MX.sym("V",(N+1)*n+N)
VX,VU = vertsplit(V,[0,(N+1)*n,(N+1)*n+N])

VXk = vertsplit(VX,n)
VUk = vertsplit(VU,1)

for k in range(N):
    
    [xf] = rk4([VXk[k],VUk[k]])

    xfp = vertsplit(xf,n/2)
    vp = vertsplit(VXk[k+1],n/2)

    g.append(xfp[0] - vp[0])
    g.append(xfp[1] - vp[1])

    g2.append(xf-VXk[k+1])

f = MXFunction([V],[veccat(g)])
f.init()

print f.jacSparsity().size()

f2 = MXFunction([V],[veccat(g2)])
f2.init()

print f2.jacSparsity().size()
```

**Comment by jgillis** [comment] 2015-07-01 10:06
There seems to be issues with sparsity sweeps in adjoint mode:

```py
from casadi import *

n = 6
x = SX.sym("x",n)
u = SX.sym("u")

g = []
g2 = []

N = 9

rk4 = SXFunction([x,u],[x+u])
rk4.init()

V = MX.sym("V",(N+1)*n+N)
VX,VU = vertsplit(V,[0,(N+1)*n,(N+1)*n+N])

VXk = vertsplit(VX,n)
VUk = vertsplit(VU,1)

for k in range(N):
    
    [xf] = rk4([VXk[k],VUk[k]])

    xfp = vertsplit(xf,n/2)
    vp = vertsplit(VXk[k+1],n/2)

    g.append(xfp[0] - vp[0])
    g.append(xfp[1] - vp[1])

    g2.append(xf-VXk[k+1])

for i in range(2):
  f = MXFunction([V],[vertcat(g)])
  f.setOption("ad_weight_sp",i)
  f.init()

  print f.jacSparsity().size()

  f2 = MXFunction([V],[vertcat(g2)])
  f2.setOption("ad_weight_sp",i)
  f2.init()

  print f2.jacSparsity().size()

```

As a workaround, I suggest `nlp.setOption("ad_weight_sp",0)`.
This option affects only the sparsity pattern evaluation, not the actual numerical computations.

**Comment by JonasKoenemann** [comment] 2015-07-01 10:09
yep that works for now! thanks for the quick solution!

**Comment by jgillis** [comment] 2015-07-01 10:12
Since this is fixed in the soon-to-be-released 2.4.0, the fix is hard to backport, and the workaround is easy, I'm closing this issue.

**Closed by jgillis** 2015-07-01 10:12 UTC

**Comment by ghorn** [comment] 2015-07-07 17:14
Does anyone know the cause of this, or when the fix happened?

**Comment by jgillis** [comment] 2015-07-07 18:01
I didnt bother to locate the exact cause and fix. The core underwent significant refactoring..

**Comment by jaeandersson** [comment] 2015-07-07 18:51
Most likely related to the work vector change.
