### ISSUE TITLE
Seg fault in python tests

### ISSUE THREAD

**Issue by dkouzoup** [casadi/casadi#1352] opened 2015-03-02 12:52 UTC
I get the following segmentation fault:

z = x, s = [[1 2]
 [3 4]]
  z = <class 'casadi.casadi.MX'>, s = <type 'numpy.ndarray'>
Segmentation fault: 11

when I run the test typemaps.py

Some info on my system
OS X Yosemite (10.10.2)
scipy (0.13.0b1)
numpy (1.8.0rc1)

**Comment by jaeandersson** [comment] 2015-03-02 18:40
Hi! This is a duplicate of #1316. There is a bug in that numpy version so you need to update numpy.

**Closed by jaeandersson** 2015-03-02 18:40 UTC

**Comment by ghorn** [comment] 2015-03-03 00:03
@dkouzoup could you confirm upgrading numpy fixes this?

**Comment by dkouzoup** [comment] 2015-03-03 08:22
I updated numpy to version 1.9.2 and scipy to 0.15.1 but the seg fault persists.

**Comment by dkouzoup** [comment] 2015-03-04 15:15
Yes, I confirm that updating to numpy 1.9.2 fixed the issue.
