### ISSUE TITLE
qpsol solver function segfault if multithreaded

### ISSUE THREAD

**Issue by markcsie** [casadi/casadi#2594] opened 2020-04-07 06:49 UTC
casadi version: 3.5.1
```
#include <iostream>
#include <casadi/casadi.hpp>
#include <thread>

void foo(const casadi::Function& solver) {
    std::vector<double> x0{0.0, 0.0};
    casadi::DMDict arg = {
        {"x0", x0},
    };
    casadi::DMDict res = solver(arg);
    std::vector<double> x_sol = std::vector<double>(res.at("x"));
    std::cout << x_sol[0] << " " << x_sol[1] << std::endl;
}

int main() {
    const casadi::SX x = casadi::SX::sym("x", 2);
    casadi::SX f = 3 * x(0) * x(0) + x(1) * x(1) + 2 * x(0) * x(1) + x(0) + 6 * x(1) + 2;
    std::vector<casadi::SX> g;
    g.emplace_back(-x(0));
    g.emplace_back(-x(1));
    g.emplace_back(-2 * x(0) + -3 * x(1) + 4);

    casadi::SXDict qp = {
        {"x", x},
        {"f", f},
        {"g", casadi::SX::vertcat(g)},
    };

    // Allocate an QP solver and buffers
    casadi::Function solver1 = casadi::qpsol("solver1", "osqp", qp);
    casadi::Function solver2 = casadi::qpsol("solver2", "osqp", qp);

    while (true) {
        std::thread t1(foo, solver1);
        std::thread t2(foo, solver2);
        t1.join();
        t2.join();
    }

    return 0;
}
```
```
#0  0x0000000000000041 in ?? ()
#1  0x00007ffff75985b6 in casadi::SharedObject::count_down() () from /usr/local/lib/libcasadi.so.3.6
#2  0x0000000000405266 in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, casadi::Matrix<double> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, casadi::Matrix<double> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, casadi::Matrix<double> > > >::_M_erase(std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, casadi::Matrix<double> > >*) ()
#3  0x0000000000404239 in foo(casadi::Function const&) ()
#4  0x00007ffff6fbbc80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff728c6ba in start_thread (arg=0x7ffff57e2700) at pthread_create.c:333
#6  0x00007ffff6a2a41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```
Segmentation fault after some iterations.
It looks like `solver1` and `solver2` share some memory which is not intuitive to the user.
Any suggestion on how to fix this?
```
while (true) {
    std::thread t1(foo, solver1);
    t1.join();
    std::thread t2(foo, solver2);
    t2.join();
}
```
is fine but not really what I want for multithreading.

**Comment by jgillis** [comment] 2020-07-20 21:39
duplicate of #2580

**Closed by jgillis** 2020-07-20 21:39 UTC
