### ISSUE TITLE
Result of nlpsol() incorrectly says constraint values are 0

### ISSUE THREAD

**Issue by chrisdembia** [casadi/casadi#2449] opened 2019-06-15 14:51 UTC
Hey Joel and Joris. It seems that the `g` output from `nlpsol()` is always 0.

The Python code

```py
from casadi import *
x = SX.sym("x",2)
f = x[0]**2 + x[1]**2
g = SX(2, 1)
g[0] = x[0]+x[1]-10
g[1] = x[0]+x[1]-5
nlp = {'x':x, 'f':f, 'g':g}
MySolver = "ipopt"
opts = {}
solver = nlpsol("solver", MySolver, nlp, opts)
sol = solver(lbg=0, ubg=0)
print("-----")
print("constraints (g) = ", sol["g"])
```

generates the output

```
...
                                   (scaled)                 (unscaled)
Objective...............:   2.8124999842691096e+01    2.8124999842691096e+01
Dual infeasibility......:   7.4999999809246143e+00    7.4999999809246143e+00
Constraint violation....:   2.5000000209745208e+00    2.5000000209745208e+00
Complementarity.........:   0.0000000000000000e+00    0.0000000000000000e+00
Overall NLP error.......:   2.5000000209745208e+00    7.4999999809246143e+00


Number of objective function evaluations             = 30
Number of objective gradient evaluations             = 4
Number of equality constraint evaluations            = 30
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 8
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 6
Total CPU secs in IPOPT (w/o function evaluations)   =      0.005
Total CPU secs in NLP function evaluations           =      0.000

EXIT: Converged to a point of local infeasibility. Problem may be infeasible.
               t_proc [s]   t_wall [s]    n_eval
       nlp_f      2.3e-05      2.9e-05        30
       nlp_g      3.5e-05      3.7e-05        30
  nlp_grad_f        1e-05        7e-06         5
  nlp_hess_l        4e-06        6e-06         5
   nlp_jac_g      1.3e-05      1.2e-05         9
      solver      0.00605      0.00597         1
-----
constraints (g) =  [0, 0]

```

The problem does not converge but CasADi says that `g = [0, 0]`

**Comment by jgillis** [comment] 2019-09-27 05:34
caused by #2386

**Comment by jgillis** [comment] 2019-09-27 05:57
Fixed now.

**Closed by jgillis** 2019-09-27 05:57 UTC
