### ISSUE TITLE
ExternalFunction using old version of generated code

### ISSUE THREAD

**Issue by sebastian-ekstrom** [casadi/casadi#1361] opened 2015-03-18 10:43 UTC
When generating code to the same file multiple times in the same program and using the generated code as ExternalFunctions, the ExternalFunction objects seem to always use the first version of the generated code even after the file has been changed. For instance, the Python script below ought to give the results 2, 3, and 3 for the three functions, but instead returns 2 for both the first and second one and then crashes on the line `nlp3_cg.setInput([1,1,1])` with the error message
```
Matrix<DataType>::setArray: Dimension mismatch.
Trying to pass 3 elements to a 2-by-1 (dense) matrix with 2 non-zeros.
```

```python
from os import system
from casadi import *

def to_external_function(fcn, name):
    print 'Generating code for', name
    system('rm ' + name + '.c ' + name + '.so')
    fcn.generateCode(name + '.c')
    system('gcc -fPIC -shared -O3 ' + name + '.c -o ' + name + '.so')
    fcn_e = ExternalFunction('./' + name + '.so')
    return fcn_e

# function 1

x1 = SX.sym('x', 2)
f1 = x1[0] + x1[1]

nlp1 = SXFunction(nlpIn(x=x1), nlpOut(f=f1))
nlp1.init()

nlp1_cg = to_external_function(nlp1, 'nlp')
nlp1_cg.init()

nlp1_cg.setInput([1,1])
nlp1_cg.evaluate()
print 'Function 1 result:', nlp1_cg.getOutput()

# function 2

x2 = SX.sym('x', 2)
f2 = x2[0] + x2[1] + 1

nlp2 = SXFunction(nlpIn(x=x2), nlpOut(f=f2))
nlp2.init()

nlp2_cg = to_external_function(nlp2, 'nlp')
nlp2_cg.init()

nlp2_cg.setInput([1,1])
nlp2_cg.evaluate()
print 'Function 2 result:', nlp2_cg.getOutput()

# function 3

x3 = SX.sym('x', 3)
f3 = x3[0] + x3[1] + x3[2]

nlp3 = SXFunction(nlpIn(x=x3), nlpOut(f=f3))
nlp3.init()

nlp3_cg = to_external_function(nlp3, 'nlp')
nlp3_cg.init()

nlp3_cg.setInput([1,1,1])
nlp3_cg.evaluate()
print 'Function 3 result:', nlp3_cg.getOutput()
```

**Comment by jaeandersson** [comment] 2015-03-19 08:20
The problem is that there can not be more than one function with the same library name in memory at the same time. In the above code, the library is freed only when `nlp1_cg` and `nlp2_cg` are deleted. This works for me for example:
```python
from os import system
from casadi import *

def to_external_function(fcn, name):
    print 'Generating code for', name
    system('rm ' + name + '.c ' + name + '.so')
    fcn.generateCode(name + '.c')
    system('gcc -fPIC -shared -O3 ' + name + '.c -o ' + name + '.so')
    fcn_e = ExternalFunction('./' + name + '.so')
    return fcn_e

# function 1

x1 = SX.sym('x', 2)
f1 = x1[0] + x1[1]

nlp1 = SXFunction(nlpIn(x=x1), nlpOut(f=f1))
nlp1.init()

nlp1_cg = to_external_function(nlp1, 'nlp')
nlp1_cg.init()

nlp1_cg.setInput([1,1])
nlp1_cg.evaluate()
print 'Function 1 result:', nlp1_cg.getOutput()
nlp1_cg = None

# function 2

x2 = SX.sym('x', 2)
f2 = x2[0] + x2[1] + 1

nlp2 = SXFunction(nlpIn(x=x2), nlpOut(f=f2))
nlp2.init()

nlp2_cg = to_external_function(nlp2, 'nlp')
nlp2_cg.init()

nlp2_cg.setInput([1,1])
nlp2_cg.evaluate()
print 'Function 2 result:', nlp2_cg.getOutput()
nlp2_cg = None

# function 3

x3 = SX.sym('x', 3)
f3 = x3[0] + x3[1] + x3[2]

nlp3 = SXFunction(nlpIn(x=x3), nlpOut(f=f3))
nlp3.init()

nlp3_cg = to_external_function(nlp3, 'nlp')
nlp3_cg.init()

nlp3_cg.setInput([1,1,1])
nlp3_cg.evaluate()
print 'Function 3 result:', nlp3_cg.getOutput()
```
I don't see that it's possible to do more than that, so I'll close the issue.

**Closed by jaeandersson** 2015-03-19 08:20 UTC

**Comment by toivoh** [comment] 2015-03-20 09:30
What is the reason for this? Is it a limitation of the operating system or does CasADi do some kind of internal caching?

**Comment by jaeandersson** [comment] 2015-03-20 13:02
I guess you can say it's a limitation of the operating system, although there might be some way for ExternalFunction to work around that limitation. There is no internal caching, the library is freed as soon as the last reference to it is deleted.

**Comment by jaeandersson** [comment] 2015-10-12 14:22
Note on this: In Python you can explicitly tell the garbage collector to run. This might be relevant here.
