### ISSUE TITLE
Please add MacOS/arm64 distribution to PyPI distribution

### ISSUE THREAD

**Issue by stevenrhall** [casadi/casadi#2932] opened 2022-07-03 01:31 UTC
Is there any chance that you could add the MacOS/arm64 os/architecture combination to the PyPI builds? Although I am able to build casadi on my M1 machine, not having it downloadable via pip install is sometimes problematic. I know that this issue has been raised before, but I haven't seen a response.

**Comment by jgillis** [comment] 2023-01-22 22:56
M1 wheels are now available for testing at https://github.com/casadi/casadi/releases/download/nightly-develop/casadi-3.5.5.dev+develop.19d47d2-cp310-none-macosx_11_0_arm64.whl
`pip install <url obtained from the appropriate whl files>`

**Comment by jgillis** [comment] 2023-01-22 22:57
Duplicate of #2932

**Comment by jgillis** [comment] 2023-01-22 22:58
Duplicate of #2829

**Closed by jgillis** 2023-01-22 22:57 UTC
