### ISSUE TITLE
Casadi master-branch not compiling (for me)

### ISSUE THREAD

**Issue by nielsvd** [casadi/casadi#1809] opened 2016-06-09 16:16 UTC
Since Travis seems to say everything's OK, some extra info:

```
$ git rev-parse HEAD
3b089f78e70aa8e41f2639a90bf07f67f0746293

$ gcc --version
gcc (GCC) 6.1.1 20160501
```

The error itself:

```
/home/niels/GIT/casadi/casadi/core/function/qpsol.cpp: In instantiation of ‘casadi::Function casadi::qpsol_nlp(const string&, const string&, const std::map<std::__cxx11::basic_string<char>, T2>&, const Dict&) [with M = casadi::Matrix<casadi::SXElem>; std::__cxx11::string = std::__cxx11::basic_string<char>; casadi::Dict = std::map<std::__cxx11::basic_string<char>, casadi::GenericType>]’:
/home/niels/GIT/casadi/casadi/core/function/qpsol.cpp:201:44:   required from here
/home/niels/GIT/casadi/casadi/core/function/qpsol.cpp:154:29: error: call of overloaded ‘qpsol(std::__cxx11::basic_string<char>, const string&, <brace-enclosed initializer list>, const Dict&)’ is ambiguous
     Function qpsol_f = qpsol(name + "_qpsol", solver,
                        ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
                              {{"h", H.sparsity()}, {"a", A.sparsity()}}, opts);
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/niels/GIT/casadi/casadi/core/function/qpsol.cpp:45:12: note: candidate: casadi::Function casadi::qpsol(const string&, const string&, const SpDict&, const Dict&)
   Function qpsol(const string& name, const string& solver,
            ^~~~~
/home/niels/GIT/casadi/casadi/core/function/qpsol.cpp:199:12: note: candidate: casadi::Function casadi::qpsol(const string&, const string&, const SXDict&, const Dict&)
   Function qpsol(const std::string& name, const std::string& solver,
            ^~~~~
/home/niels/GIT/casadi/casadi/core/function/qpsol.cpp:204:12: note: candidate: casadi::Function casadi::qpsol(const string&, const string&, const MXDict&, const Dict&)
   Function qpsol(const std::string& name, const std::string& solver,
            ^~~~~
/home/niels/GIT/casadi/casadi/core/function/qpsol.cpp: In instantiation of ‘casadi::Function casadi::qpsol_nlp(const string&, const string&, const std::map<std::__cxx11::basic_string<char>, T2>&, const Dict&) [with M = casadi::MX; std::__cxx11::string = std::__cxx11::basic_string<char>; casadi::Dict = std::map<std::__cxx11::basic_string<char>, casadi::GenericType>]’:
/home/niels/GIT/casadi/casadi/core/function/qpsol.cpp:206:44:   required from here
/home/niels/GIT/casadi/casadi/core/function/qpsol.cpp:154:29: error: call of overloaded ‘qpsol(std::__cxx11::basic_string<char>, const string&, <brace-enclosed initializer list>, const Dict&)’ is ambiguous
     Function qpsol_f = qpsol(name + "_qpsol", solver,
                        ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
                              {{"h", H.sparsity()}, {"a", A.sparsity()}}, opts);
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/niels/GIT/casadi/casadi/core/function/qpsol.cpp:45:12: note: candidate: casadi::Function casadi::qpsol(const string&, const string&, const SpDict&, const Dict&)
   Function qpsol(const string& name, const string& solver,
            ^~~~~
/home/niels/GIT/casadi/casadi/core/function/qpsol.cpp:199:12: note: candidate: casadi::Function casadi::qpsol(const string&, const string&, const SXDict&, const Dict&)
   Function qpsol(const std::string& name, const std::string& solver,
            ^~~~~
/home/niels/GIT/casadi/casadi/core/function/qpsol.cpp:204:12: note: candidate: casadi::Function casadi::qpsol(const string&, const string&, const MXDict&, const Dict&)
   Function qpsol(const std::string& name, const std::string& solver,
            ^~~~~
casadi/core/CMakeFiles/casadi.dir/build.make:1454: recipe for target 'casadi/core/CMakeFiles/casadi.dir/function/qpsol.cpp.o' failed
```

**Comment by jaeandersson** [comment] 2016-06-09 16:38
I guess it's related to the fact that you're using GCC 6. I tried just resolving the ambiguity in the `issue_1809` branch - can you compile and check if that works?

Note that this particular function overload isn't ambiguous for the develop branch since the overload of `qpsol` that takes sparsities has been renamed `conic`.

**Comment by jaeandersson** [comment] 2016-06-09 16:38
https://github.com/casadi/casadi/compare/issue_1809

**Comment by nielsvd** [comment] 2016-06-09 19:34
On the right track, although I get another error further down the line:
```
/home/niels/GIT/casadi/casadi/solvers/sqpmethod.cpp: In member function ‘virtual void casadi::Sqpmethod::init(const Dict&)’:
/home/niels/GIT/casadi/casadi/solvers/sqpmethod.cpp:183:33: error: call of overloaded ‘qpsol(const char [6], std::__cxx11::string&, <brace-enclosed initializer list>, casadi::Dict&)’ is ambiguous
                    qpsol_options);
                                 ^
In file included from /home/niels/GIT/casadi/casadi/solvers/sqpmethod.cpp:30:0:
/home/niels/GIT/casadi/./casadi/core/function/qpsol.hpp:75:26: note: candidate: casadi::Function casadi::qpsol(const string&, const string&, const SpDict&, const Dict&)
   CASADI_EXPORT Function qpsol(const std::string& name, const std::string& solver,
                          ^~~~~
/home/niels/GIT/casadi/./casadi/core/function/qpsol.hpp:77:26: note: candidate: casadi::Function casadi::qpsol(const string&, const string&, const SXDict&, const Dict&)
   CASADI_EXPORT Function qpsol(const std::string& name, const std::string& solver,
                          ^~~~~
/home/niels/GIT/casadi/./casadi/core/function/qpsol.hpp:79:26: note: candidate: casadi::Function casadi::qpsol(const string&, const string&, const MXDict&, const Dict&)
   CASADI_EXPORT Function qpsol(const std::string& name, const std::string& solver,
                          ^~~~~
[ 86%] Building CXX object casadi/solvers/CMakeFiles/casadi_rootfinder_newton.dir/newton_meta.cpp.o
casadi/solvers/CMakeFiles/casadi_nlpsol_sqpmethod.dir/build.make:62: recipe for target 'casadi/solvers/CMakeFiles/casadi_nlpsol_sqpmethod.dir/sqpmethod.cpp.o' failed
make[2]: *** [casadi/solvers/CMakeFiles/casadi_nlpsol_sqpmethod.dir/sqpmethod.cpp.o] Error 1
CMakeFiles/Makefile2:2637: recipe for target 'casadi/solvers/CMakeFiles/casadi_nlpsol_sqpmethod.dir/all' failed
make[1]: *** [casadi/solvers/CMakeFiles/casadi_nlpsol_sqpmethod.dir/all] Error 2

```

**Comment by jaeandersson** [comment] 2016-06-09 20:32
After that second commit, are all issues resolved?

**Comment by nielsvd** [comment] 2016-06-09 20:34
I can build casadi without any issues now.

**Comment by jaeandersson** [comment] 2016-06-09 20:56
@jgillis Does this merit a minor release? Not sure if it's an issue for everybody with GCC 6.

**Comment by jgillis** [comment] 2016-06-10 05:38
Can do. But are this fixes valid, or is this a regression of gcc?

**Comment by jgillis** [comment] 2016-06-10 10:12
Seems to compile fine with `gcc-6 (Ubuntu 6.1.1-3ubuntu11~12.04.1) 6.1.1 20160511` on travis ( https://travis-ci.org/casadi/casadi/jobs/136653557 )

**Closed** 2017-05-22 08:36 UTC
