### ISSUE TITLE
need a convenient way to do NLP codegen

### ISSUE THREAD

**Issue by ghorn** [casadi/casadi#1487] opened 2015-07-17 01:03 UTC
The only example doing NLP codegen is here https://github.com/casadi/casadi/blob/develop/docs/examples/cplusplus/nlp_codegen.cpp#L81-L102, so I'm going to assume it's currently the canonical way to do it.

Is it right that the hessian in this example is actually the hessian of the objective, and not the hessian of the lagrangian?

It would be really awesome if there was an easier way of doing nlp codegen.

**Comment by jaeandersson** [comment] 2015-07-17 10:24
> so I'm going to assume it's currently the canonical way to do it.

Yes, more or less. There is also the `embeddable_codegen` example.

> Is it right that the hessian in this example is actually the hessian of the objective, and not the hessian of the lagrangian?

Incorrect. It's the Hessian of the Lagrangian, not of the objective.

> It would be really awesome if there was an easier way of doing nlp codegen.

I think the correct way to go about it is to add support for just-in-time compilation, via `libclang`. To call the system compiler using the `system` command is not portable.

**Comment by jaeandersson** [comment] 2015-07-17 10:35
I'll close this as it is essentially a duplicate of #949.

**Closed by jaeandersson** 2015-07-17 10:35 UTC
Labels: duplicate, enhancement
